apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: kube-public
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin12345
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: kube-public
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kube-public
  labels:
    app: postgres
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:12.2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kube-public
  labels:
    app: postgres
  annotations:
    prometheus.io/probe: "true"
spec:
  type: ClusterIP
  selector:
   app: postgres
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP