{{- $_ := include "init" . }}
{{- $ingress := .Values.data.ingress }}
{{- $service := .Values.data.service }}
{{- if and $ingress.enabled $service.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selectorLabels" . | nindent 4 }}
    {{- with $ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ingress.class }}
  rules:
  {{- $domains := splitList " " $ingress.domain}}
  {{- range $i, $domain := $domains }}
  {{- $url := urlParse (print "http://" $domain)}}
  - host: {{ $url.hostname }}
    http:
      paths:
      - path: {{ coalesce $url.path "/" }}
        pathType: Prefix
        backend: 
          service:
            name: {{ $.Release.Name }}
            port:
              number: {{ $ingress.port }}
  {{- end }}
  {{- if hasKey $ingress "tls" }}
  tls:
  {{- if contains " " $ingress.tls }}
  {{- range $i, $tls := splitList " " $ingress.tls }}
  {{- if and (lt $i (len $domains)) (ne $tls "-") }}
  - secretName: {{ $tls }}
    hosts:
    - {{ index $domains $i }}
  {{- end }}
  {{- end }}
  {{- else }}
  - secretName: {{ $ingress.tls }}
    hosts:
    {{- toYaml $domains | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}