apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.125.4
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: node1
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: kubernetes
certificatesDir: /etc/kubernetes/pki
kubernetesVersion: 1.28.0
controlPlaneEndpoint: "192.168.125.4:6443"
networking:
  dnsDomain: cluster.local
  podSubnet: 172.18.0.0/16
  serviceSubnet: 172.19.0.0/16
apiServer:
  certSANs:
  - "192.168.124.4"
  - "192.168.125.4"
  - "192.168.125.5"
  - "192.168.125.6"
  - "192.168.125.7"
  - "192.168.125.8"
  - "192.168.125.9"
  extraArgs:
    authorization-mode: "Node,RBAC"
  timeoutForControlPlane: 4m0s
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
controllerManager: 
  extraArgs:
    bind-address: "0.0.0.0"
scheduler: 
  extraArgs:
    bind-address: "0.0.0.0"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metricsBindAddress: 0.0.0.0:10249